### ISSUE TITLE
Error in Make-pdf.ulp

### ISSUE THREAD

**Issue by Victorb101** [BuckeyeCurrent/Component-libraries#74]
@aaronbeekay When I run make-pdf I get an error:

"Division by Zero"

On line 74 of .ulp:

		scale = min( pageW / boardW, pageH / boardH );

I'm not sure where boardW & boardH come from.  Have I done something wrong or can the script be changed to fix this?

**Comment by aaronbeekay** [comment]
@Victorb101 Stupid integer error. Fixed in 2ed3403d9f67686a682738b711f3d92ad3a6caed and merged in #80. The script should work now.
